### ISSUE TITLE
Try pypi mirrors when pypi fails

### ISSUE THREAD

**Issue by brainsik** [brainsik/virtualenv-burrito#18]
pypi is currently down, and virtualenv-burrito has no built-in way of using pypi mirrors in the mean time.

**Comment by mattrobenolt** [comment]
This can be closed, and mirrors aren't as necessary as before since pypi is fronted by a CDN. :)

**Comment by brainsik** [comment]
Good to know. It's unlikely I'll get around to this anyway. :-)
