### ISSUE TITLE
setup tools should probably be upgraded.

### ISSUE THREAD

**Issue by robert-halliday** [brainsik/virtualenv-burrito#54]
Thanks for providing venvburrito to the community!

We ran into a problem whose root cause was an old version of setuptools being installed into

~/.venvburrito/lib/python2.7/site-packages/

From https://github.com/brainsik/virtualenv-burrito/blob/master/versions.csv, I see that the version being installed is 12.3 which doesn't support the egg_info command.

**Comment by brainsik** [comment]
What version do you need?

**Comment by robert-halliday** [comment]
We installed 15.0 and the problem went away.  In case I didn’t mention it before, the problem is that setup.py for a module that we were installing was called with “egg_info” as the command.  This isn’t available in 12.3.  Uninstalling setuptools from the .venvburritto directory allowed us to upgrade the version in the virtualenv and that fixed the problem.  (If we didn’t uninstall it, then “pip install –upgrade setuptools” complained that it couldn’t upgrade the setuptools because it would be updating files outside of the virtualenv).  At its root, it’s probably some sort of mismatch between the versions of pip and setuptools, but I didn’t dig into it far enough to say for certain.  Upgrading was good enough for us.  You’d know better if it’s the globally better solution.

 

Thanks!

Robert Halliday

**Comment by brainsik** [comment]
Fixed in 25a08e6bafaad8204656578784b0210fdfa96fd2
