### ISSUE TITLE
Upgrading pip

### ISSUE THREAD

**Issue by silentninja** [brainsik/virtualenv-burrito#56]
The current pip version is 7.0.1.But whenever i make a new virtual environment I get 1.4.1 pip version.When I run virtualenv-burrito upgrade command it says everything is up to date.Is there anyway to set default pip version and how do i upgrade virtualenv-burrito package?

**Comment by brainsik** [comment]
The pip package is installed by virtualenv as part of the process that creates the virtualenv. To upgrade pip in a virtualenv, run `pip install -U pip`.
