### ISSUE TITLE
So why `pip install virtualenvwrapper` is not enough?

### ISSUE THREAD

**Issue by techtonik** [brainsik/virtualenv-burrito#60]
Came here from Python Guide and don't get the problem that this package is trying to solve. Is there a log of command session that shows what is wrong with `pip install virtualenvwrapper` and right with this package?

**Comment by brainsik** [comment]
The project description describes the goal pretty well — "One command to have a working virtualenv + virtualenvwrapper environment." If you're happy setting up your environment another way, then do that! :-)

**Comment by techtonik** [comment]
@brainsik yea, but that command doesn't work on Windows, and it is not clear how that's different from `pip install virtualenvwrapper`.

**Comment by brainsik** [comment]
Ah, sorry, this project doesn't currently support Windows. 

It's quite different from `pip install virtualenvwrapper` since it's handling the case where there is no `pip` application. The idea is you can boot up a fresh *nix system, run the curl command, and start coding. No perquisites.

**Comment by techtonik** [comment]
I thought that `pip` is installed with Python by default now, but perhaps it is only me. Still `python` is still needed for it to work, right?

**Comment by brainsik** [comment]
`pip` only comes with recent versions of Python. All *nix systems ship with Python.

**Comment by techtonik** [comment]
Ok. Now it is a little bit more clear than before.

**Comment by techtonik** [comment]
But it could be explained in docs!
=)

**Comment by techtonik** [comment]
Like `sadly complicated` could be a link to actual complicated session.

**Comment by brainsik** [comment]
I added a "requirements" section at top (19a673dc783e6ff3dd3d951104043758498efc1a) before closing this. :-)

As for the "sadly complicated" part, I figured the list of different packages one might end up dealing with was scary enough. :-)
