### ISSUE TITLE
How to properly upgrade pip to the latest?

### ISSUE THREAD

**Issue by antonywu** [brainsik/virtualenv-burrito#61]
When I did `pip freeze`, I received the following warning

`You are using pip version 7.1.2, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`

And when I did `pip install --upgrade pip`, I got
`Not uninstalling pip at /Users/antony/.venvburrito/lib/python2.7/site-packages/pip-7.1.2-py2.7.egg, outside environment /Users/antony/.virtualenvs/my_venv/bin/..`

And then if I do `deactivate`, followed by `virtualenv-burrito upgrade`, I got
```
+ pip will upgrade (1.5.6 -> 7.1.2)
  Downloading pip-7.1.2.tar.gz …
* Upgrading pip …
  Installing pip-7.1.2
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.mailmap'
warning: no previously-included files found matching '.travis.yml'
warning: no previously-included files found matching 'pip/_vendor/Makefile'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files found matching 'dev-requirements.txt'
no previously-included directories found matching '.travis'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'contrib'
no previously-included directories found matching 'tasks'
no previously-included directories found matching 'tests'

Fin.
```

**Comment by brainsik** [comment]
Please run upgrade again to get the latest versions. Thanks!
