### ISSUE TITLE
Uninstall virtualenv-burrito

### ISSUE THREAD

**Issue by RAbraham** [brainsik/virtualenv-burrito#63]
Hi,
I made the mistake of having pre-existing virtualenv etc and installing virtualenv-burrito. I want to start from scratch. How can I uninstall all existing modifications(e.g PATH) and others easily without hunting for all burrito references.

Thanks!

**Comment by brainsik** [comment]
Two steps:
1. `rm -rf ~/.venvburrito`
1. Edit your shell profile (e.g., `.profile` or `.bash_profile`) and remove the small chunk of code that was added.
