### ISSUE TITLE
SyntaxError: invalid syntax on setup

### ISSUE THREAD

**Issue by sselvaggi** [brainsik/virtualenv-burrito#64]
$ sudo sh virtualenv-burrito.sh

throws:

 File "<string>", line 1
    import platform;print ".".join(platform.python_version().split(".")[:2])

**Comment by brainsik** [comment]
First off, this is _not_ meant to run under sudo. It's meant to run in a standard user account. Are you intentionally trying to install this for the root user?

Second, this is a BASH script, but you're running it under `sh` instead of `bash`. Probably, `sh` doesn't understand the syntax.

**Comment by urbantom** [comment]
Hi, this is not a bash/sh related issue. The element
`import platform;print ".".join(platform.python_version().split(".")[:2])`
is included in the line:
`pyver=$(python -c 'import platform;print ".".join(platform.python_version().split(".")[:2])')`
Hence the error comes form the python environemnt. More specifically from the print impementation in the Python 3. In Python 3, print is a function, you need to call it like print(".".join(platform.python_version().split(".")[:2])).
@sselvaggi should check additionally if there was Python 2 or 3 installed.
