### ISSUE TITLE
Error installing with /bin/csh shell

### ISSUE THREAD

**Issue by MBARIMike** [brainsik/virtualenv-burrito#69]
Following instructions I get:

```
> echo $SHELL
/bin/csh
> curl -sL https://raw.githubusercontent.com/brainsik/virtualenv-burrito/master/virtualenv-burrito.sh | $SHELL
set: Variable name must begin with a letter.
```

Does virtualenv-burrito work with the csh shell?

**Comment by mattrobenolt** [comment]
Hey @MBARIMike, we don't support `csh`, but would be happy to accept a pull request here for it. I don't have experience with `csh`, so not sure I could add it myself.

**Comment by MBARIMike** [comment]
I'm switching over to bash so don't be looking for a PR from me. Thanks for a nice package.
