### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by mrkaiser** [brainsik/virtualenv-burrito#72]
The script should support Python3 as many linux distros now default to Python3

**Comment by mattrobenolt** [comment]
Pull requests accepted. :) I don't use python3 myself, so I'm not even sure what would need to be involved to support it.

**Comment by brainsik** [comment]
@mrkaiser I'm curious to hear your use case? What sort of system are you on? Why aren't you using the system provided tools to get virtualenv support?

Otherwise, some Python 3 work is already tracked in #24.
